### PR TITLE
Remove iree-org.github.io redirect to openxla.

### PR DESCRIPTION
**Pull request by ScottTodd**
* We're moving the IREE repo back to iree-org so we don't need to redirect https://iree-org.github.io to https://openxla.github.io (which still does not exist). We also don't need to redirect e.g. https://iree-org.github.io/iree/building-from-source to https://openxla.github.io/iree/building-from-source (then again to https://iree.dev/building-from-source/)
* We will likely move again, from iree-org into some new location (at which point we can either keep a redirect repo like this around or make a clean break)
* The pip-release-index page now points at https://iree.dev/pip-release-links.html, which should be stable across any GitHub organization moves

### CODE REVIEW

**Comment by ScottTodd** [comment]
cc @jpienaar

**Review by jpienaar — APPROVED** [review]
Is pip release links deletion required?

**Comment by ScottTodd** [comment]
> Is pip release links deletion required?

I considered updating the version here to match what tip of tree has, but I think deleting the file is equivalent to openxla _not_ having a file/redirect, which is working today.

Here are the scenarios:

* `-f https://iree.dev/pip-release-links.html`: this points at the latest location
* `-f https://openxla.github.io/iree/pip-release-links.html`: this is redirected (by the web host?)
  * I think this works in pip?
* `-f https://iree-org.github.io/iree/pip-release-links.html`: this is redirected once to openxla (`HTTP 301: Moved Permanently`) then again to iree.dev (`HTTP 307: Temporary Redirect`)
  * This works in browsers but not in pip

Ah, GitHub isn't showing the diff on that file. There is a comment at the top:
```html
  <head>
    <!--
      Try to do a client-side redirect if we can, but that won't work for the
      most important usage via pip, so we also clone the historical state of
      this page at the time of the migration. Users will have to update their
      URL to get new releases and this comment should give them some hint.
    -->
    <meta http-equiv="refresh" content="0;url=https://openxla.github.io/iree/pip-release-links.html">
    <title>Redirecting to https://openxla.github.io/iree/pip-release-links.html</title>
  </head>
```

**Comment by ScottTodd** [comment]
(I don't have write access to this repo, so feel free to merge if you are happy with the changes)

**Pull request merged**
